// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Utils.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Utils_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Utils_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Utils_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Utils_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Utils_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_Utils_2eproto_metadata_getter(int index);
class oAttribute;
struct oAttributeDefaultTypeInternal;
extern oAttributeDefaultTypeInternal _oAttribute_default_instance_;
class oGameUnit;
struct oGameUnitDefaultTypeInternal;
extern oGameUnitDefaultTypeInternal _oGameUnit_default_instance_;
class oQuaternion;
struct oQuaternionDefaultTypeInternal;
extern oQuaternionDefaultTypeInternal _oQuaternion_default_instance_;
class oValue;
struct oValueDefaultTypeInternal;
extern oValueDefaultTypeInternal _oValue_default_instance_;
class oVector2;
struct oVector2DefaultTypeInternal;
extern oVector2DefaultTypeInternal _oVector2_default_instance_;
class oVector3;
struct oVector3DefaultTypeInternal;
extern oVector3DefaultTypeInternal _oVector3_default_instance_;
class oVector4;
struct oVector4DefaultTypeInternal;
extern oVector4DefaultTypeInternal _oVector4_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::oAttribute* Arena::CreateMaybeMessage<::oAttribute>(Arena*);
template<> ::oGameUnit* Arena::CreateMaybeMessage<::oGameUnit>(Arena*);
template<> ::oQuaternion* Arena::CreateMaybeMessage<::oQuaternion>(Arena*);
template<> ::oValue* Arena::CreateMaybeMessage<::oValue>(Arena*);
template<> ::oVector2* Arena::CreateMaybeMessage<::oVector2>(Arena*);
template<> ::oVector3* Arena::CreateMaybeMessage<::oVector3>(Arena*);
template<> ::oVector4* Arena::CreateMaybeMessage<::oVector4>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class oVector2 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oVector2) */ {
 public:
  inline oVector2() : oVector2(nullptr) {}
  virtual ~oVector2();
  explicit constexpr oVector2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  oVector2(const oVector2& from);
  oVector2(oVector2&& from) noexcept
    : oVector2() {
    *this = ::std::move(from);
  }

  inline oVector2& operator=(const oVector2& from) {
    CopyFrom(from);
    return *this;
  }
  inline oVector2& operator=(oVector2&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const oVector2& default_instance() {
    return *internal_default_instance();
  }
  static inline const oVector2* internal_default_instance() {
    return reinterpret_cast<const oVector2*>(
               &_oVector2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(oVector2& a, oVector2& b) {
    a.Swap(&b);
  }
  inline void Swap(oVector2* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(oVector2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline oVector2* New() const final {
    return CreateMaybeMessage<oVector2>(nullptr);
  }

  oVector2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<oVector2>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const oVector2& from);
  void MergeFrom(const oVector2& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(oVector2* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oVector2";
  }
  protected:
  explicit oVector2(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Utils_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:oVector2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Utils_2eproto;
};
// -------------------------------------------------------------------

class oVector3 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oVector3) */ {
 public:
  inline oVector3() : oVector3(nullptr) {}
  virtual ~oVector3();
  explicit constexpr oVector3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  oVector3(const oVector3& from);
  oVector3(oVector3&& from) noexcept
    : oVector3() {
    *this = ::std::move(from);
  }

  inline oVector3& operator=(const oVector3& from) {
    CopyFrom(from);
    return *this;
  }
  inline oVector3& operator=(oVector3&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const oVector3& default_instance() {
    return *internal_default_instance();
  }
  static inline const oVector3* internal_default_instance() {
    return reinterpret_cast<const oVector3*>(
               &_oVector3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(oVector3& a, oVector3& b) {
    a.Swap(&b);
  }
  inline void Swap(oVector3* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(oVector3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline oVector3* New() const final {
    return CreateMaybeMessage<oVector3>(nullptr);
  }

  oVector3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<oVector3>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const oVector3& from);
  void MergeFrom(const oVector3& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(oVector3* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oVector3";
  }
  protected:
  explicit oVector3(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Utils_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:oVector3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Utils_2eproto;
};
// -------------------------------------------------------------------

class oVector4 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oVector4) */ {
 public:
  inline oVector4() : oVector4(nullptr) {}
  virtual ~oVector4();
  explicit constexpr oVector4(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  oVector4(const oVector4& from);
  oVector4(oVector4&& from) noexcept
    : oVector4() {
    *this = ::std::move(from);
  }

  inline oVector4& operator=(const oVector4& from) {
    CopyFrom(from);
    return *this;
  }
  inline oVector4& operator=(oVector4&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const oVector4& default_instance() {
    return *internal_default_instance();
  }
  static inline const oVector4* internal_default_instance() {
    return reinterpret_cast<const oVector4*>(
               &_oVector4_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(oVector4& a, oVector4& b) {
    a.Swap(&b);
  }
  inline void Swap(oVector4* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(oVector4* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline oVector4* New() const final {
    return CreateMaybeMessage<oVector4>(nullptr);
  }

  oVector4* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<oVector4>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const oVector4& from);
  void MergeFrom(const oVector4& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(oVector4* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oVector4";
  }
  protected:
  explicit oVector4(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Utils_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float w = 4;
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // @@protoc_insertion_point(class_scope:oVector4)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Utils_2eproto;
};
// -------------------------------------------------------------------

class oQuaternion PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oQuaternion) */ {
 public:
  inline oQuaternion() : oQuaternion(nullptr) {}
  virtual ~oQuaternion();
  explicit constexpr oQuaternion(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  oQuaternion(const oQuaternion& from);
  oQuaternion(oQuaternion&& from) noexcept
    : oQuaternion() {
    *this = ::std::move(from);
  }

  inline oQuaternion& operator=(const oQuaternion& from) {
    CopyFrom(from);
    return *this;
  }
  inline oQuaternion& operator=(oQuaternion&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const oQuaternion& default_instance() {
    return *internal_default_instance();
  }
  static inline const oQuaternion* internal_default_instance() {
    return reinterpret_cast<const oQuaternion*>(
               &_oQuaternion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(oQuaternion& a, oQuaternion& b) {
    a.Swap(&b);
  }
  inline void Swap(oQuaternion* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(oQuaternion* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline oQuaternion* New() const final {
    return CreateMaybeMessage<oQuaternion>(nullptr);
  }

  oQuaternion* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<oQuaternion>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const oQuaternion& from);
  void MergeFrom(const oQuaternion& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(oQuaternion* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oQuaternion";
  }
  protected:
  explicit oQuaternion(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Utils_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float w = 4;
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // @@protoc_insertion_point(class_scope:oQuaternion)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Utils_2eproto;
};
// -------------------------------------------------------------------

class oValue PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oValue) */ {
 public:
  inline oValue() : oValue(nullptr) {}
  virtual ~oValue();
  explicit constexpr oValue(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  oValue(const oValue& from);
  oValue(oValue&& from) noexcept
    : oValue() {
    *this = ::std::move(from);
  }

  inline oValue& operator=(const oValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline oValue& operator=(oValue&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const oValue& default_instance() {
    return *internal_default_instance();
  }
  static inline const oValue* internal_default_instance() {
    return reinterpret_cast<const oValue*>(
               &_oValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(oValue& a, oValue& b) {
    a.Swap(&b);
  }
  inline void Swap(oValue* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(oValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline oValue* New() const final {
    return CreateMaybeMessage<oValue>(nullptr);
  }

  oValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<oValue>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const oValue& from);
  void MergeFrom(const oValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(oValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oValue";
  }
  protected:
  explicit oValue(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Utils_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStringFieldNumber = 5,
    kVector2FieldNumber = 7,
    kVector3FieldNumber = 8,
    kVector4FieldNumber = 9,
    kIntFieldNumber = 2,
    kTypeFieldNumber = 1,
    kFloatFieldNumber = 4,
    kUIntFieldNumber = 3,
    kBoolFieldNumber = 6,
  };
  // string _String = 5;
  void clear__string();
  const std::string& _string() const;
  void set__string(const std::string& value);
  void set__string(std::string&& value);
  void set__string(const char* value);
  void set__string(const char* value, size_t size);
  std::string* mutable__string();
  std::string* release__string();
  void set_allocated__string(std::string* _string);
  private:
  const std::string& _internal__string() const;
  void _internal_set__string(const std::string& value);
  std::string* _internal_mutable__string();
  public:

  // .oVector2 _Vector2 = 7;
  bool has__vector2() const;
  private:
  bool _internal_has__vector2() const;
  public:
  void clear__vector2();
  const ::oVector2& _vector2() const;
  ::oVector2* release__vector2();
  ::oVector2* mutable__vector2();
  void set_allocated__vector2(::oVector2* _vector2);
  private:
  const ::oVector2& _internal__vector2() const;
  ::oVector2* _internal_mutable__vector2();
  public:
  void unsafe_arena_set_allocated__vector2(
      ::oVector2* _vector2);
  ::oVector2* unsafe_arena_release__vector2();

  // .oVector3 _Vector3 = 8;
  bool has__vector3() const;
  private:
  bool _internal_has__vector3() const;
  public:
  void clear__vector3();
  const ::oVector3& _vector3() const;
  ::oVector3* release__vector3();
  ::oVector3* mutable__vector3();
  void set_allocated__vector3(::oVector3* _vector3);
  private:
  const ::oVector3& _internal__vector3() const;
  ::oVector3* _internal_mutable__vector3();
  public:
  void unsafe_arena_set_allocated__vector3(
      ::oVector3* _vector3);
  ::oVector3* unsafe_arena_release__vector3();

  // .oVector4 _Vector4 = 9;
  bool has__vector4() const;
  private:
  bool _internal_has__vector4() const;
  public:
  void clear__vector4();
  const ::oVector4& _vector4() const;
  ::oVector4* release__vector4();
  ::oVector4* mutable__vector4();
  void set_allocated__vector4(::oVector4* _vector4);
  private:
  const ::oVector4& _internal__vector4() const;
  ::oVector4* _internal_mutable__vector4();
  public:
  void unsafe_arena_set_allocated__vector4(
      ::oVector4* _vector4);
  ::oVector4* unsafe_arena_release__vector4();

  // int64 _Int = 2;
  void clear__int();
  ::PROTOBUF_NAMESPACE_ID::int64 _int() const;
  void set__int(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal__int() const;
  void _internal_set__int(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 _Type = 1;
  void clear__type();
  ::PROTOBUF_NAMESPACE_ID::int32 _type() const;
  void set__type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal__type() const;
  void _internal_set__type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float _Float = 4;
  void clear__float();
  float _float() const;
  void set__float(float value);
  private:
  float _internal__float() const;
  void _internal_set__float(float value);
  public:

  // uint64 _UInt = 3;
  void clear__uint();
  ::PROTOBUF_NAMESPACE_ID::uint64 _uint() const;
  void set__uint(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal__uint() const;
  void _internal_set__uint(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool _Bool = 6;
  void clear__bool();
  bool _bool() const;
  void set__bool(bool value);
  private:
  bool _internal__bool() const;
  void _internal_set__bool(bool value);
  public:

  // @@protoc_insertion_point(class_scope:oValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr _string_;
  ::oVector2* _vector2_;
  ::oVector3* _vector3_;
  ::oVector4* _vector4_;
  ::PROTOBUF_NAMESPACE_ID::int64 _int_;
  ::PROTOBUF_NAMESPACE_ID::int32 _type_;
  float _float_;
  ::PROTOBUF_NAMESPACE_ID::uint64 _uint_;
  bool _bool_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Utils_2eproto;
};
// -------------------------------------------------------------------

class oAttribute PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oAttribute) */ {
 public:
  inline oAttribute() : oAttribute(nullptr) {}
  virtual ~oAttribute();
  explicit constexpr oAttribute(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  oAttribute(const oAttribute& from);
  oAttribute(oAttribute&& from) noexcept
    : oAttribute() {
    *this = ::std::move(from);
  }

  inline oAttribute& operator=(const oAttribute& from) {
    CopyFrom(from);
    return *this;
  }
  inline oAttribute& operator=(oAttribute&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const oAttribute& default_instance() {
    return *internal_default_instance();
  }
  static inline const oAttribute* internal_default_instance() {
    return reinterpret_cast<const oAttribute*>(
               &_oAttribute_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(oAttribute& a, oAttribute& b) {
    a.Swap(&b);
  }
  inline void Swap(oAttribute* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(oAttribute* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline oAttribute* New() const final {
    return CreateMaybeMessage<oAttribute>(nullptr);
  }

  oAttribute* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<oAttribute>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const oAttribute& from);
  void MergeFrom(const oAttribute& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(oAttribute* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oAttribute";
  }
  protected:
  explicit oAttribute(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Utils_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 2,
    kIndexFieldNumber = 1,
  };
  // .oValue value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const ::oValue& value() const;
  ::oValue* release_value();
  ::oValue* mutable_value();
  void set_allocated_value(::oValue* value);
  private:
  const ::oValue& _internal_value() const;
  ::oValue* _internal_mutable_value();
  public:
  void unsafe_arena_set_allocated_value(
      ::oValue* value);
  ::oValue* unsafe_arena_release_value();

  // int32 index = 1;
  void clear_index();
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_index() const;
  void _internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:oAttribute)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::oValue* value_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Utils_2eproto;
};
// -------------------------------------------------------------------

class oGameUnit PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oGameUnit) */ {
 public:
  inline oGameUnit() : oGameUnit(nullptr) {}
  virtual ~oGameUnit();
  explicit constexpr oGameUnit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  oGameUnit(const oGameUnit& from);
  oGameUnit(oGameUnit&& from) noexcept
    : oGameUnit() {
    *this = ::std::move(from);
  }

  inline oGameUnit& operator=(const oGameUnit& from) {
    CopyFrom(from);
    return *this;
  }
  inline oGameUnit& operator=(oGameUnit&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const oGameUnit& default_instance() {
    return *internal_default_instance();
  }
  static inline const oGameUnit* internal_default_instance() {
    return reinterpret_cast<const oGameUnit*>(
               &_oGameUnit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(oGameUnit& a, oGameUnit& b) {
    a.Swap(&b);
  }
  inline void Swap(oGameUnit* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(oGameUnit* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline oGameUnit* New() const final {
    return CreateMaybeMessage<oGameUnit>(nullptr);
  }

  oGameUnit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<oGameUnit>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const oGameUnit& from);
  void MergeFrom(const oGameUnit& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(oGameUnit* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oGameUnit";
  }
  protected:
  explicit oGameUnit(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Utils_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAttributesFieldNumber = 7,
    kNameFieldNumber = 8,
    kPositionFieldNumber = 6,
    kGuidFieldNumber = 1,
    kConfigIdFieldNumber = 3,
    kTypeFieldNumber = 2,
    kStateFieldNumber = 4,
    kAngleFieldNumber = 5,
  };
  // repeated .oAttribute attributes = 7;
  int attributes_size() const;
  private:
  int _internal_attributes_size() const;
  public:
  void clear_attributes();
  ::oAttribute* mutable_attributes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oAttribute >*
      mutable_attributes();
  private:
  const ::oAttribute& _internal_attributes(int index) const;
  ::oAttribute* _internal_add_attributes();
  public:
  const ::oAttribute& attributes(int index) const;
  ::oAttribute* add_attributes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oAttribute >&
      attributes() const;

  // string name = 8;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .oVector2 position = 6;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::oVector2& position() const;
  ::oVector2* release_position();
  ::oVector2* mutable_position();
  void set_allocated_position(::oVector2* position);
  private:
  const ::oVector2& _internal_position() const;
  ::oVector2* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::oVector2* position);
  ::oVector2* unsafe_arena_release_position();

  // uint64 guid = 1;
  void clear_guid();
  ::PROTOBUF_NAMESPACE_ID::uint64 guid() const;
  void set_guid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_guid() const;
  void _internal_set_guid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int64 configId = 3;
  void clear_configid();
  ::PROTOBUF_NAMESPACE_ID::int64 configid() const;
  void set_configid(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_configid() const;
  void _internal_set_configid(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 type = 2;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 state = 4;
  void clear_state();
  ::PROTOBUF_NAMESPACE_ID::int32 state() const;
  void set_state(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_state() const;
  void _internal_set_state(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 angle = 5;
  void clear_angle();
  ::PROTOBUF_NAMESPACE_ID::int32 angle() const;
  void set_angle(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_angle() const;
  void _internal_set_angle(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:oGameUnit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oAttribute > attributes_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::oVector2* position_;
  ::PROTOBUF_NAMESPACE_ID::uint64 guid_;
  ::PROTOBUF_NAMESPACE_ID::int64 configid_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  ::PROTOBUF_NAMESPACE_ID::int32 state_;
  ::PROTOBUF_NAMESPACE_ID::int32 angle_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Utils_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// oVector2

// float x = 1;
inline void oVector2::clear_x() {
  x_ = 0;
}
inline float oVector2::_internal_x() const {
  return x_;
}
inline float oVector2::x() const {
  // @@protoc_insertion_point(field_get:oVector2.x)
  return _internal_x();
}
inline void oVector2::_internal_set_x(float value) {
  
  x_ = value;
}
inline void oVector2::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:oVector2.x)
}

// float y = 2;
inline void oVector2::clear_y() {
  y_ = 0;
}
inline float oVector2::_internal_y() const {
  return y_;
}
inline float oVector2::y() const {
  // @@protoc_insertion_point(field_get:oVector2.y)
  return _internal_y();
}
inline void oVector2::_internal_set_y(float value) {
  
  y_ = value;
}
inline void oVector2::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:oVector2.y)
}

// -------------------------------------------------------------------

// oVector3

// float x = 1;
inline void oVector3::clear_x() {
  x_ = 0;
}
inline float oVector3::_internal_x() const {
  return x_;
}
inline float oVector3::x() const {
  // @@protoc_insertion_point(field_get:oVector3.x)
  return _internal_x();
}
inline void oVector3::_internal_set_x(float value) {
  
  x_ = value;
}
inline void oVector3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:oVector3.x)
}

// float y = 2;
inline void oVector3::clear_y() {
  y_ = 0;
}
inline float oVector3::_internal_y() const {
  return y_;
}
inline float oVector3::y() const {
  // @@protoc_insertion_point(field_get:oVector3.y)
  return _internal_y();
}
inline void oVector3::_internal_set_y(float value) {
  
  y_ = value;
}
inline void oVector3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:oVector3.y)
}

// float z = 3;
inline void oVector3::clear_z() {
  z_ = 0;
}
inline float oVector3::_internal_z() const {
  return z_;
}
inline float oVector3::z() const {
  // @@protoc_insertion_point(field_get:oVector3.z)
  return _internal_z();
}
inline void oVector3::_internal_set_z(float value) {
  
  z_ = value;
}
inline void oVector3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:oVector3.z)
}

// -------------------------------------------------------------------

// oVector4

// float x = 1;
inline void oVector4::clear_x() {
  x_ = 0;
}
inline float oVector4::_internal_x() const {
  return x_;
}
inline float oVector4::x() const {
  // @@protoc_insertion_point(field_get:oVector4.x)
  return _internal_x();
}
inline void oVector4::_internal_set_x(float value) {
  
  x_ = value;
}
inline void oVector4::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:oVector4.x)
}

// float y = 2;
inline void oVector4::clear_y() {
  y_ = 0;
}
inline float oVector4::_internal_y() const {
  return y_;
}
inline float oVector4::y() const {
  // @@protoc_insertion_point(field_get:oVector4.y)
  return _internal_y();
}
inline void oVector4::_internal_set_y(float value) {
  
  y_ = value;
}
inline void oVector4::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:oVector4.y)
}

// float z = 3;
inline void oVector4::clear_z() {
  z_ = 0;
}
inline float oVector4::_internal_z() const {
  return z_;
}
inline float oVector4::z() const {
  // @@protoc_insertion_point(field_get:oVector4.z)
  return _internal_z();
}
inline void oVector4::_internal_set_z(float value) {
  
  z_ = value;
}
inline void oVector4::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:oVector4.z)
}

// float w = 4;
inline void oVector4::clear_w() {
  w_ = 0;
}
inline float oVector4::_internal_w() const {
  return w_;
}
inline float oVector4::w() const {
  // @@protoc_insertion_point(field_get:oVector4.w)
  return _internal_w();
}
inline void oVector4::_internal_set_w(float value) {
  
  w_ = value;
}
inline void oVector4::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:oVector4.w)
}

// -------------------------------------------------------------------

// oQuaternion

// float x = 1;
inline void oQuaternion::clear_x() {
  x_ = 0;
}
inline float oQuaternion::_internal_x() const {
  return x_;
}
inline float oQuaternion::x() const {
  // @@protoc_insertion_point(field_get:oQuaternion.x)
  return _internal_x();
}
inline void oQuaternion::_internal_set_x(float value) {
  
  x_ = value;
}
inline void oQuaternion::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:oQuaternion.x)
}

// float y = 2;
inline void oQuaternion::clear_y() {
  y_ = 0;
}
inline float oQuaternion::_internal_y() const {
  return y_;
}
inline float oQuaternion::y() const {
  // @@protoc_insertion_point(field_get:oQuaternion.y)
  return _internal_y();
}
inline void oQuaternion::_internal_set_y(float value) {
  
  y_ = value;
}
inline void oQuaternion::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:oQuaternion.y)
}

// float z = 3;
inline void oQuaternion::clear_z() {
  z_ = 0;
}
inline float oQuaternion::_internal_z() const {
  return z_;
}
inline float oQuaternion::z() const {
  // @@protoc_insertion_point(field_get:oQuaternion.z)
  return _internal_z();
}
inline void oQuaternion::_internal_set_z(float value) {
  
  z_ = value;
}
inline void oQuaternion::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:oQuaternion.z)
}

// float w = 4;
inline void oQuaternion::clear_w() {
  w_ = 0;
}
inline float oQuaternion::_internal_w() const {
  return w_;
}
inline float oQuaternion::w() const {
  // @@protoc_insertion_point(field_get:oQuaternion.w)
  return _internal_w();
}
inline void oQuaternion::_internal_set_w(float value) {
  
  w_ = value;
}
inline void oQuaternion::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:oQuaternion.w)
}

// -------------------------------------------------------------------

// oValue

// int32 _Type = 1;
inline void oValue::clear__type() {
  _type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oValue::_internal__type() const {
  return _type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oValue::_type() const {
  // @@protoc_insertion_point(field_get:oValue._Type)
  return _internal__type();
}
inline void oValue::_internal_set__type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  _type_ = value;
}
inline void oValue::set__type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set__type(value);
  // @@protoc_insertion_point(field_set:oValue._Type)
}

// int64 _Int = 2;
inline void oValue::clear__int() {
  _int_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 oValue::_internal__int() const {
  return _int_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 oValue::_int() const {
  // @@protoc_insertion_point(field_get:oValue._Int)
  return _internal__int();
}
inline void oValue::_internal_set__int(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  _int_ = value;
}
inline void oValue::set__int(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set__int(value);
  // @@protoc_insertion_point(field_set:oValue._Int)
}

// uint64 _UInt = 3;
inline void oValue::clear__uint() {
  _uint_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 oValue::_internal__uint() const {
  return _uint_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 oValue::_uint() const {
  // @@protoc_insertion_point(field_get:oValue._UInt)
  return _internal__uint();
}
inline void oValue::_internal_set__uint(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  _uint_ = value;
}
inline void oValue::set__uint(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set__uint(value);
  // @@protoc_insertion_point(field_set:oValue._UInt)
}

// float _Float = 4;
inline void oValue::clear__float() {
  _float_ = 0;
}
inline float oValue::_internal__float() const {
  return _float_;
}
inline float oValue::_float() const {
  // @@protoc_insertion_point(field_get:oValue._Float)
  return _internal__float();
}
inline void oValue::_internal_set__float(float value) {
  
  _float_ = value;
}
inline void oValue::set__float(float value) {
  _internal_set__float(value);
  // @@protoc_insertion_point(field_set:oValue._Float)
}

// string _String = 5;
inline void oValue::clear__string() {
  _string_.ClearToEmpty();
}
inline const std::string& oValue::_string() const {
  // @@protoc_insertion_point(field_get:oValue._String)
  return _internal__string();
}
inline void oValue::set__string(const std::string& value) {
  _internal_set__string(value);
  // @@protoc_insertion_point(field_set:oValue._String)
}
inline std::string* oValue::mutable__string() {
  // @@protoc_insertion_point(field_mutable:oValue._String)
  return _internal_mutable__string();
}
inline const std::string& oValue::_internal__string() const {
  return _string_.Get();
}
inline void oValue::_internal_set__string(const std::string& value) {
  
  _string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void oValue::set__string(std::string&& value) {
  
  _string_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:oValue._String)
}
inline void oValue::set__string(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  _string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:oValue._String)
}
inline void oValue::set__string(const char* value,
    size_t size) {
  
  _string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:oValue._String)
}
inline std::string* oValue::_internal_mutable__string() {
  
  return _string_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* oValue::release__string() {
  // @@protoc_insertion_point(field_release:oValue._String)
  return _string_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void oValue::set_allocated__string(std::string* _string) {
  if (_string != nullptr) {
    
  } else {
    
  }
  _string_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), _string,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:oValue._String)
}

// bool _Bool = 6;
inline void oValue::clear__bool() {
  _bool_ = false;
}
inline bool oValue::_internal__bool() const {
  return _bool_;
}
inline bool oValue::_bool() const {
  // @@protoc_insertion_point(field_get:oValue._Bool)
  return _internal__bool();
}
inline void oValue::_internal_set__bool(bool value) {
  
  _bool_ = value;
}
inline void oValue::set__bool(bool value) {
  _internal_set__bool(value);
  // @@protoc_insertion_point(field_set:oValue._Bool)
}

// .oVector2 _Vector2 = 7;
inline bool oValue::_internal_has__vector2() const {
  return this != internal_default_instance() && _vector2_ != nullptr;
}
inline bool oValue::has__vector2() const {
  return _internal_has__vector2();
}
inline void oValue::clear__vector2() {
  if (GetArena() == nullptr && _vector2_ != nullptr) {
    delete _vector2_;
  }
  _vector2_ = nullptr;
}
inline const ::oVector2& oValue::_internal__vector2() const {
  const ::oVector2* p = _vector2_;
  return p != nullptr ? *p : reinterpret_cast<const ::oVector2&>(
      ::_oVector2_default_instance_);
}
inline const ::oVector2& oValue::_vector2() const {
  // @@protoc_insertion_point(field_get:oValue._Vector2)
  return _internal__vector2();
}
inline void oValue::unsafe_arena_set_allocated__vector2(
    ::oVector2* _vector2) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_vector2_);
  }
  _vector2_ = _vector2;
  if (_vector2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:oValue._Vector2)
}
inline ::oVector2* oValue::release__vector2() {
  
  ::oVector2* temp = _vector2_;
  _vector2_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::oVector2* oValue::unsafe_arena_release__vector2() {
  // @@protoc_insertion_point(field_release:oValue._Vector2)
  
  ::oVector2* temp = _vector2_;
  _vector2_ = nullptr;
  return temp;
}
inline ::oVector2* oValue::_internal_mutable__vector2() {
  
  if (_vector2_ == nullptr) {
    auto* p = CreateMaybeMessage<::oVector2>(GetArena());
    _vector2_ = p;
  }
  return _vector2_;
}
inline ::oVector2* oValue::mutable__vector2() {
  // @@protoc_insertion_point(field_mutable:oValue._Vector2)
  return _internal_mutable__vector2();
}
inline void oValue::set_allocated__vector2(::oVector2* _vector2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete _vector2_;
  }
  if (_vector2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(_vector2);
    if (message_arena != submessage_arena) {
      _vector2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, _vector2, submessage_arena);
    }
    
  } else {
    
  }
  _vector2_ = _vector2;
  // @@protoc_insertion_point(field_set_allocated:oValue._Vector2)
}

// .oVector3 _Vector3 = 8;
inline bool oValue::_internal_has__vector3() const {
  return this != internal_default_instance() && _vector3_ != nullptr;
}
inline bool oValue::has__vector3() const {
  return _internal_has__vector3();
}
inline void oValue::clear__vector3() {
  if (GetArena() == nullptr && _vector3_ != nullptr) {
    delete _vector3_;
  }
  _vector3_ = nullptr;
}
inline const ::oVector3& oValue::_internal__vector3() const {
  const ::oVector3* p = _vector3_;
  return p != nullptr ? *p : reinterpret_cast<const ::oVector3&>(
      ::_oVector3_default_instance_);
}
inline const ::oVector3& oValue::_vector3() const {
  // @@protoc_insertion_point(field_get:oValue._Vector3)
  return _internal__vector3();
}
inline void oValue::unsafe_arena_set_allocated__vector3(
    ::oVector3* _vector3) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_vector3_);
  }
  _vector3_ = _vector3;
  if (_vector3) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:oValue._Vector3)
}
inline ::oVector3* oValue::release__vector3() {
  
  ::oVector3* temp = _vector3_;
  _vector3_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::oVector3* oValue::unsafe_arena_release__vector3() {
  // @@protoc_insertion_point(field_release:oValue._Vector3)
  
  ::oVector3* temp = _vector3_;
  _vector3_ = nullptr;
  return temp;
}
inline ::oVector3* oValue::_internal_mutable__vector3() {
  
  if (_vector3_ == nullptr) {
    auto* p = CreateMaybeMessage<::oVector3>(GetArena());
    _vector3_ = p;
  }
  return _vector3_;
}
inline ::oVector3* oValue::mutable__vector3() {
  // @@protoc_insertion_point(field_mutable:oValue._Vector3)
  return _internal_mutable__vector3();
}
inline void oValue::set_allocated__vector3(::oVector3* _vector3) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete _vector3_;
  }
  if (_vector3) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(_vector3);
    if (message_arena != submessage_arena) {
      _vector3 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, _vector3, submessage_arena);
    }
    
  } else {
    
  }
  _vector3_ = _vector3;
  // @@protoc_insertion_point(field_set_allocated:oValue._Vector3)
}

// .oVector4 _Vector4 = 9;
inline bool oValue::_internal_has__vector4() const {
  return this != internal_default_instance() && _vector4_ != nullptr;
}
inline bool oValue::has__vector4() const {
  return _internal_has__vector4();
}
inline void oValue::clear__vector4() {
  if (GetArena() == nullptr && _vector4_ != nullptr) {
    delete _vector4_;
  }
  _vector4_ = nullptr;
}
inline const ::oVector4& oValue::_internal__vector4() const {
  const ::oVector4* p = _vector4_;
  return p != nullptr ? *p : reinterpret_cast<const ::oVector4&>(
      ::_oVector4_default_instance_);
}
inline const ::oVector4& oValue::_vector4() const {
  // @@protoc_insertion_point(field_get:oValue._Vector4)
  return _internal__vector4();
}
inline void oValue::unsafe_arena_set_allocated__vector4(
    ::oVector4* _vector4) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_vector4_);
  }
  _vector4_ = _vector4;
  if (_vector4) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:oValue._Vector4)
}
inline ::oVector4* oValue::release__vector4() {
  
  ::oVector4* temp = _vector4_;
  _vector4_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::oVector4* oValue::unsafe_arena_release__vector4() {
  // @@protoc_insertion_point(field_release:oValue._Vector4)
  
  ::oVector4* temp = _vector4_;
  _vector4_ = nullptr;
  return temp;
}
inline ::oVector4* oValue::_internal_mutable__vector4() {
  
  if (_vector4_ == nullptr) {
    auto* p = CreateMaybeMessage<::oVector4>(GetArena());
    _vector4_ = p;
  }
  return _vector4_;
}
inline ::oVector4* oValue::mutable__vector4() {
  // @@protoc_insertion_point(field_mutable:oValue._Vector4)
  return _internal_mutable__vector4();
}
inline void oValue::set_allocated__vector4(::oVector4* _vector4) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete _vector4_;
  }
  if (_vector4) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(_vector4);
    if (message_arena != submessage_arena) {
      _vector4 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, _vector4, submessage_arena);
    }
    
  } else {
    
  }
  _vector4_ = _vector4;
  // @@protoc_insertion_point(field_set_allocated:oValue._Vector4)
}

// -------------------------------------------------------------------

// oAttribute

// int32 index = 1;
inline void oAttribute::clear_index() {
  index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oAttribute::_internal_index() const {
  return index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oAttribute::index() const {
  // @@protoc_insertion_point(field_get:oAttribute.index)
  return _internal_index();
}
inline void oAttribute::_internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  index_ = value;
}
inline void oAttribute::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:oAttribute.index)
}

// .oValue value = 2;
inline bool oAttribute::_internal_has_value() const {
  return this != internal_default_instance() && value_ != nullptr;
}
inline bool oAttribute::has_value() const {
  return _internal_has_value();
}
inline void oAttribute::clear_value() {
  if (GetArena() == nullptr && value_ != nullptr) {
    delete value_;
  }
  value_ = nullptr;
}
inline const ::oValue& oAttribute::_internal_value() const {
  const ::oValue* p = value_;
  return p != nullptr ? *p : reinterpret_cast<const ::oValue&>(
      ::_oValue_default_instance_);
}
inline const ::oValue& oAttribute::value() const {
  // @@protoc_insertion_point(field_get:oAttribute.value)
  return _internal_value();
}
inline void oAttribute::unsafe_arena_set_allocated_value(
    ::oValue* value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(value_);
  }
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:oAttribute.value)
}
inline ::oValue* oAttribute::release_value() {
  
  ::oValue* temp = value_;
  value_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::oValue* oAttribute::unsafe_arena_release_value() {
  // @@protoc_insertion_point(field_release:oAttribute.value)
  
  ::oValue* temp = value_;
  value_ = nullptr;
  return temp;
}
inline ::oValue* oAttribute::_internal_mutable_value() {
  
  if (value_ == nullptr) {
    auto* p = CreateMaybeMessage<::oValue>(GetArena());
    value_ = p;
  }
  return value_;
}
inline ::oValue* oAttribute::mutable_value() {
  // @@protoc_insertion_point(field_mutable:oAttribute.value)
  return _internal_mutable_value();
}
inline void oAttribute::set_allocated_value(::oValue* value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete value_;
  }
  if (value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(value);
    if (message_arena != submessage_arena) {
      value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    
  } else {
    
  }
  value_ = value;
  // @@protoc_insertion_point(field_set_allocated:oAttribute.value)
}

// -------------------------------------------------------------------

// oGameUnit

// uint64 guid = 1;
inline void oGameUnit::clear_guid() {
  guid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 oGameUnit::_internal_guid() const {
  return guid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 oGameUnit::guid() const {
  // @@protoc_insertion_point(field_get:oGameUnit.guid)
  return _internal_guid();
}
inline void oGameUnit::_internal_set_guid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  guid_ = value;
}
inline void oGameUnit::set_guid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_guid(value);
  // @@protoc_insertion_point(field_set:oGameUnit.guid)
}

// int32 type = 2;
inline void oGameUnit::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oGameUnit::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oGameUnit::type() const {
  // @@protoc_insertion_point(field_get:oGameUnit.type)
  return _internal_type();
}
inline void oGameUnit::_internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
}
inline void oGameUnit::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:oGameUnit.type)
}

// int64 configId = 3;
inline void oGameUnit::clear_configid() {
  configid_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 oGameUnit::_internal_configid() const {
  return configid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 oGameUnit::configid() const {
  // @@protoc_insertion_point(field_get:oGameUnit.configId)
  return _internal_configid();
}
inline void oGameUnit::_internal_set_configid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  configid_ = value;
}
inline void oGameUnit::set_configid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_configid(value);
  // @@protoc_insertion_point(field_set:oGameUnit.configId)
}

// int32 state = 4;
inline void oGameUnit::clear_state() {
  state_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oGameUnit::_internal_state() const {
  return state_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oGameUnit::state() const {
  // @@protoc_insertion_point(field_get:oGameUnit.state)
  return _internal_state();
}
inline void oGameUnit::_internal_set_state(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  state_ = value;
}
inline void oGameUnit::set_state(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:oGameUnit.state)
}

// int32 angle = 5;
inline void oGameUnit::clear_angle() {
  angle_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oGameUnit::_internal_angle() const {
  return angle_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 oGameUnit::angle() const {
  // @@protoc_insertion_point(field_get:oGameUnit.angle)
  return _internal_angle();
}
inline void oGameUnit::_internal_set_angle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  angle_ = value;
}
inline void oGameUnit::set_angle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:oGameUnit.angle)
}

// .oVector2 position = 6;
inline bool oGameUnit::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool oGameUnit::has_position() const {
  return _internal_has_position();
}
inline void oGameUnit::clear_position() {
  if (GetArena() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::oVector2& oGameUnit::_internal_position() const {
  const ::oVector2* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::oVector2&>(
      ::_oVector2_default_instance_);
}
inline const ::oVector2& oGameUnit::position() const {
  // @@protoc_insertion_point(field_get:oGameUnit.position)
  return _internal_position();
}
inline void oGameUnit::unsafe_arena_set_allocated_position(
    ::oVector2* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:oGameUnit.position)
}
inline ::oVector2* oGameUnit::release_position() {
  
  ::oVector2* temp = position_;
  position_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::oVector2* oGameUnit::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:oGameUnit.position)
  
  ::oVector2* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::oVector2* oGameUnit::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::oVector2>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::oVector2* oGameUnit::mutable_position() {
  // @@protoc_insertion_point(field_mutable:oGameUnit.position)
  return _internal_mutable_position();
}
inline void oGameUnit::set_allocated_position(::oVector2* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:oGameUnit.position)
}

// repeated .oAttribute attributes = 7;
inline int oGameUnit::_internal_attributes_size() const {
  return attributes_.size();
}
inline int oGameUnit::attributes_size() const {
  return _internal_attributes_size();
}
inline void oGameUnit::clear_attributes() {
  attributes_.Clear();
}
inline ::oAttribute* oGameUnit::mutable_attributes(int index) {
  // @@protoc_insertion_point(field_mutable:oGameUnit.attributes)
  return attributes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oAttribute >*
oGameUnit::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable_list:oGameUnit.attributes)
  return &attributes_;
}
inline const ::oAttribute& oGameUnit::_internal_attributes(int index) const {
  return attributes_.Get(index);
}
inline const ::oAttribute& oGameUnit::attributes(int index) const {
  // @@protoc_insertion_point(field_get:oGameUnit.attributes)
  return _internal_attributes(index);
}
inline ::oAttribute* oGameUnit::_internal_add_attributes() {
  return attributes_.Add();
}
inline ::oAttribute* oGameUnit::add_attributes() {
  // @@protoc_insertion_point(field_add:oGameUnit.attributes)
  return _internal_add_attributes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oAttribute >&
oGameUnit::attributes() const {
  // @@protoc_insertion_point(field_list:oGameUnit.attributes)
  return attributes_;
}

// string name = 8;
inline void oGameUnit::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& oGameUnit::name() const {
  // @@protoc_insertion_point(field_get:oGameUnit.name)
  return _internal_name();
}
inline void oGameUnit::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:oGameUnit.name)
}
inline std::string* oGameUnit::mutable_name() {
  // @@protoc_insertion_point(field_mutable:oGameUnit.name)
  return _internal_mutable_name();
}
inline const std::string& oGameUnit::_internal_name() const {
  return name_.Get();
}
inline void oGameUnit::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void oGameUnit::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:oGameUnit.name)
}
inline void oGameUnit::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:oGameUnit.name)
}
inline void oGameUnit::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:oGameUnit.name)
}
inline std::string* oGameUnit::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* oGameUnit::release_name() {
  // @@protoc_insertion_point(field_release:oGameUnit.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void oGameUnit::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:oGameUnit.name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Utils_2eproto
