// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from data.proto</summary>
public static partial class DataReflection {

  #region Descriptor
  /// <summary>File descriptor for data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpkYXRhLnByb3RvIkYKBm9WYWx1ZRIMCgRpbnRfGAEgASgDEg4KBmZsb2F0",
          "XxgCIAEoAhIPCgdzdHJpbmdfGAMgASgJEg0KBWJvb2xfGAQgASgIIkkKCm9B",
          "dHRyaWJ1dGUSFAoEdHlwZRgBIAEoDjIGLmVUeXBlEg0KBWluZGV4GAIgASgF",
          "EhYKBXZhbHVlGAMgASgLMgcub1ZhbHVlKkEKBWVUeXBlEgsKB19faW50X18Q",
          "ABINCglfX2Zsb2F0X18QARIOCgpfX3N0cmluZ19fEAISDAoIX19ib29sX18Q",
          "A2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::eType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::oValue), global::oValue.Parser, new[]{ "Int", "Float", "String", "Bool" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::oAttribute), global::oAttribute.Parser, new[]{ "Type", "Index", "Value" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum eType {
  [pbr::OriginalName("__int__")] Int = 0,
  [pbr::OriginalName("__float__")] Float = 1,
  [pbr::OriginalName("__string__")] String = 2,
  [pbr::OriginalName("__bool__")] Bool = 3,
}

#endregion

#region Messages
public sealed partial class oValue : pb::IMessage<oValue>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<oValue> _parser = new pb::MessageParser<oValue>(() => new oValue());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<oValue> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public oValue() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public oValue(oValue other) : this() {
    int_ = other.int_;
    float_ = other.float_;
    string_ = other.string_;
    bool_ = other.bool_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public oValue Clone() {
    return new oValue(this);
  }

  /// <summary>Field number for the "int_" field.</summary>
  public const int IntFieldNumber = 1;
  private long int_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Int {
    get { return int_; }
    set {
      int_ = value;
    }
  }

  /// <summary>Field number for the "float_" field.</summary>
  public const int FloatFieldNumber = 2;
  private float float_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Float {
    get { return float_; }
    set {
      float_ = value;
    }
  }

  /// <summary>Field number for the "string_" field.</summary>
  public const int StringFieldNumber = 3;
  private string string_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String {
    get { return string_; }
    set {
      string_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bool_" field.</summary>
  public const int BoolFieldNumber = 4;
  private bool bool_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Bool {
    get { return bool_; }
    set {
      bool_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as oValue);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(oValue other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Int != other.Int) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Float, other.Float)) return false;
    if (String != other.String) return false;
    if (Bool != other.Bool) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Int != 0L) hash ^= Int.GetHashCode();
    if (Float != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Float);
    if (String.Length != 0) hash ^= String.GetHashCode();
    if (Bool != false) hash ^= Bool.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Int != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Int);
    }
    if (Float != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Float);
    }
    if (String.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(String);
    }
    if (Bool != false) {
      output.WriteRawTag(32);
      output.WriteBool(Bool);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Int != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Int);
    }
    if (Float != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Float);
    }
    if (String.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(String);
    }
    if (Bool != false) {
      output.WriteRawTag(32);
      output.WriteBool(Bool);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Int != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int);
    }
    if (Float != 0F) {
      size += 1 + 4;
    }
    if (String.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(String);
    }
    if (Bool != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(oValue other) {
    if (other == null) {
      return;
    }
    if (other.Int != 0L) {
      Int = other.Int;
    }
    if (other.Float != 0F) {
      Float = other.Float;
    }
    if (other.String.Length != 0) {
      String = other.String;
    }
    if (other.Bool != false) {
      Bool = other.Bool;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Int = input.ReadInt64();
          break;
        }
        case 21: {
          Float = input.ReadFloat();
          break;
        }
        case 26: {
          String = input.ReadString();
          break;
        }
        case 32: {
          Bool = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Int = input.ReadInt64();
          break;
        }
        case 21: {
          Float = input.ReadFloat();
          break;
        }
        case 26: {
          String = input.ReadString();
          break;
        }
        case 32: {
          Bool = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class oAttribute : pb::IMessage<oAttribute>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<oAttribute> _parser = new pb::MessageParser<oAttribute>(() => new oAttribute());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<oAttribute> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public oAttribute() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public oAttribute(oAttribute other) : this() {
    type_ = other.type_;
    index_ = other.index_;
    value_ = other.value_ != null ? other.value_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public oAttribute Clone() {
    return new oAttribute(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::eType type_ = global::eType.Int;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::eType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "index" field.</summary>
  public const int IndexFieldNumber = 2;
  private int index_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Index {
    get { return index_; }
    set {
      index_ = value;
    }
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 3;
  private global::oValue value_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::oValue Value {
    get { return value_; }
    set {
      value_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as oAttribute);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(oAttribute other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Index != other.Index) return false;
    if (!object.Equals(Value, other.Value)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::eType.Int) hash ^= Type.GetHashCode();
    if (Index != 0) hash ^= Index.GetHashCode();
    if (value_ != null) hash ^= Value.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::eType.Int) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Index != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Index);
    }
    if (value_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::eType.Int) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Index != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Index);
    }
    if (value_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::eType.Int) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Index != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
    }
    if (value_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Value);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(oAttribute other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::eType.Int) {
      Type = other.Type;
    }
    if (other.Index != 0) {
      Index = other.Index;
    }
    if (other.value_ != null) {
      if (value_ == null) {
        Value = new global::oValue();
      }
      Value.MergeFrom(other.Value);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::eType) input.ReadEnum();
          break;
        }
        case 16: {
          Index = input.ReadInt32();
          break;
        }
        case 26: {
          if (value_ == null) {
            Value = new global::oValue();
          }
          input.ReadMessage(Value);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::eType) input.ReadEnum();
          break;
        }
        case 16: {
          Index = input.ReadInt32();
          break;
        }
        case 26: {
          if (value_ == null) {
            Value = new global::oValue();
          }
          input.ReadMessage(Value);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
