using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
namespace AutoConfig
{
    public class Bullet
    {
        public const Int64 INVALID_CONFIG_ID = 0;
        public readonly Int64 _ID;
        public readonly string _Name;
        public readonly AutoEnum.eBallistics _Ballistics;
        public readonly float _Speed;
        public readonly AutoEnum.eRangeType _RangeType;
        public readonly float _Radius;
        public readonly float _SectorAngle;
        public readonly float[] _RectangleSize;
        public readonly bool _IsCollision;
        public readonly Int64 _CollisionCount;
        public readonly Int64 _CollisionInterval;
        public readonly Int64 _UpdateInterval;
        public readonly float _MaxTurnAngle;
        public readonly AutoEnum.eDamageType _DamageType;
        public readonly Int64[] _BuffConfigIDs;
        public readonly Int64[] _DeathLaunchers;
        public readonly AutoEnum.eTargetType[] _TargetType;
        public readonly Int64 _Angle;
        public readonly float _AddSpeed;
        public readonly string _BulletPrefab;
        public readonly float _BulletMutiple;
        public readonly Int64 _EndPrefab;
        public readonly Int64 _LifeCycle;
        public readonly Int64 _DestroyTime;
        public readonly float _HeightParameter;
        public readonly AutoEnum.ePhysicType[] _PhysicType;
        public readonly float _SkillDamage;
        public readonly Int64 _TouchEffect;
        public readonly Int64 _TrailerEffect;
        public readonly bool _EffectTarget;
        public readonly Int64 _IntervalTime;
        public readonly bool _IsMultiple;
        public readonly string _WhereLoop;
        public readonly string _PreviousLoop;
        public readonly string _LaterLoop;
        public readonly Int64 _LoopTime;
        public readonly float _ShortRadius;
        public readonly bool _IsHitLoop;
        public readonly AutoEnum.eLifePanType _LifePanType;
        public readonly Int64 _AddHurtLife;
        public readonly bool _IsDisappera;
        public readonly bool _IsFollowHost;
        public readonly Int64 _ChangeZ;
        public readonly string _CanMoveLayer;
        public Bullet(Int64 ID, string Name, AutoEnum.eBallistics Ballistics, float Speed, AutoEnum.eRangeType RangeType, float Radius, float SectorAngle, float[] RectangleSize, bool IsCollision, Int64 CollisionCount, Int64 CollisionInterval, Int64 UpdateInterval, float MaxTurnAngle, AutoEnum.eDamageType DamageType, Int64[] BuffConfigIDs, Int64[] DeathLaunchers, AutoEnum.eTargetType[] TargetType, Int64 Angle, float AddSpeed, string BulletPrefab, float BulletMutiple, Int64 EndPrefab, Int64 LifeCycle, Int64 DestroyTime, float HeightParameter, AutoEnum.ePhysicType[] PhysicType, float SkillDamage, Int64 TouchEffect, Int64 TrailerEffect, bool EffectTarget, Int64 IntervalTime, bool IsMultiple, string WhereLoop, string PreviousLoop, string LaterLoop, Int64 LoopTime, float ShortRadius, bool IsHitLoop, AutoEnum.eLifePanType LifePanType, Int64 AddHurtLife, bool IsDisappera, bool IsFollowHost, Int64 ChangeZ, string CanMoveLayer)
        {
            _ID = ID;
            _Name = Name;
            _Ballistics = Ballistics;
            _Speed = Speed;
            _RangeType = RangeType;
            _Radius = Radius;
            _SectorAngle = SectorAngle;
            _RectangleSize = RectangleSize;
            _IsCollision = IsCollision;
            _CollisionCount = CollisionCount;
            _CollisionInterval = CollisionInterval;
            _UpdateInterval = UpdateInterval;
            _MaxTurnAngle = MaxTurnAngle;
            _DamageType = DamageType;
            _BuffConfigIDs = BuffConfigIDs;
            _DeathLaunchers = DeathLaunchers;
            _TargetType = TargetType;
            _Angle = Angle;
            _AddSpeed = AddSpeed;
            _BulletPrefab = BulletPrefab;
            _BulletMutiple = BulletMutiple;
            _EndPrefab = EndPrefab;
            _LifeCycle = LifeCycle;
            _DestroyTime = DestroyTime;
            _HeightParameter = HeightParameter;
            _PhysicType = PhysicType;
            _SkillDamage = SkillDamage;
            _TouchEffect = TouchEffect;
            _TrailerEffect = TrailerEffect;
            _EffectTarget = EffectTarget;
            _IntervalTime = IntervalTime;
            _IsMultiple = IsMultiple;
            _WhereLoop = WhereLoop;
            _PreviousLoop = PreviousLoop;
            _LaterLoop = LaterLoop;
            _LoopTime = LoopTime;
            _ShortRadius = ShortRadius;
            _IsHitLoop = IsHitLoop;
            _LifePanType = LifePanType;
            _AddHurtLife = AddHurtLife;
            _IsDisappera = IsDisappera;
            _IsFollowHost = IsFollowHost;
            _ChangeZ = ChangeZ;
            _CanMoveLayer = CanMoveLayer;
        }
        public readonly static ReadOnlyDictionary<Int64, Bullet> Datas = new ReadOnlyDictionary<Int64, Bullet>(
            new Dictionary<Int64, Bullet>() {
                {11001, new Bullet(11001, "小哥测试血阵", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Ellipse, 5f, 40f, new float[] {10f,10f}, true, 0, 375, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "Spine/VFX/Prefabs/AttackB", 2f, 0, 3500, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 0.7f, 1009, 0, false, 325, true, "blood_3", "blood_2", "blood_4", 2000, 3f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11002, new Bullet(11002, "小哥测试声波攻击", AutoEnum.eBallistics.Line, 3f, AutoEnum.eRangeType.Cube, 6f, 40f, new float[] {4.65f,5.5f}, true, 0, 220, 10, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1021}, new Int64[] {2}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, -0.85f, "Spine/VFX/Prefabs/AttackC", 1f, 0, 1700, 500, 1.5f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.None}, 2.5f, 1010, 0, false, 425, false, "", "", "", 0, 5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11003, new Bullet(11003, "跟踪弹", AutoEnum.eBallistics.Track, 4f, AutoEnum.eRangeType.None, 2f, 40f, new float[] {10f,10f}, true, 1, 10, 25, 7f, AutoEnum.eDamageType.Physic, new Int64[] {1001}, new Int64[] {2}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "Effect/Prefabs/Environment/Fire/Cartoon/PowerupGlow2", 1f, 1011, 5000, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 4f, 1011, 1014, true, 102, false, "", "", "", 0, 5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11004, new Bullet(11004, "小哥测试普攻踢腿", AutoEnum.eBallistics.Line, 9f, AutoEnum.eRangeType.Cube, 4f, 40f, new float[] {0f,0f}, true, 0, 3000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1025}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, -2f, "Spine/VFX/Prefabs/AttackA", 1f, 0, 770, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 4f, 1009, 0, false, 750, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11005, new Bullet(11005, "血滴", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.None, 0f, 40f, new float[] {10f,10f}, true, 5, 10, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1004}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "Spine/VFX/Prefabs/AttackB_Blood", 1f, 0, 500, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 4f, 0, 0, false, 103, false, "", "", "", 0, 0f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11006, new Bullet(11006, "普攻1", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Cube, 2f, 210f, new float[] {7f,6.75f}, true, 0, 115, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "", 1f, 0, 585, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 0.4f, 1009, 0, false, 265, false, "", "", "", 0, 1.65f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11007, new Bullet(11007, "普攻2", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Cube, 2f, 210f, new float[] {7f,6.75f}, true, 0, 115, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "", 1f, 0, 400, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1f, 1009, 0, false, 1201, false, "", "", "", 0, 1.65f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11008, new Bullet(11008, "普攻3", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Cube, 2f, 210f, new float[] {7f,6.75f}, true, 0, 115, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "", 1f, 0, 400, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.35f, 1009, 0, false, 1202, false, "", "", "", 0, 1.65f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11009, new Bullet(11009, "野怪地刺", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Ellipse, 1.25f, 40f, new float[] {10f,10f}, true, 0, 350, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1004}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "Spine/VFX/Monster/Prefabs/JiuTouSheBai/Caltrop", 2f, 0, 900, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1500, true, "Snake_Caltrop-stay-A", "Snake_Caltrop-A", "Snake_Caltrop-back-A", 675, 1.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11010, new Bullet(11010, "九头扫人B", AutoEnum.eBallistics.Line, 1.25f, AutoEnum.eRangeType.Ellipse, 2.75f, 210f, new float[] {10f,10f}, true, 0, 335, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1024}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "", 1f, 0, 1800, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1900, false, "", "", "", 0, 13.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11011, new Bullet(11011, "九头扫人D", AutoEnum.eBallistics.Line, 1.25f, AutoEnum.eRangeType.Ellipse, 2.75f, 210f, new float[] {10f,10f}, true, 0, 335, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1024}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 180, 0f, "", 1f, 0, 1800, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1900, false, "", "", "", 0, 12f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11012, new Bullet(11012, "九头蛇柏抬头纯表现", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Ellipse, 0f, 210f, new float[] {10f,10f}, true, 0, 350, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1001}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "", 1f, 0, 5000, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 0f, 1009, 0, false, 1202, false, "", "", "", 0, 0f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11013, new Bullet(11013, "藤曼触手怪", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Ellipse, 1.25f, 210f, new float[] {10f,10f}, true, 1, 350, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1001,1023}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "Spine/VFX/Monster/Prefabs/JiuTouSheBai/Bunding", 1f, 1017, 1200, 850, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.3f, 1009, 0, false, 1300, true, "tengman-stay", "tengman-in", "tengman-out", 4200, 1.5f, true, AutoEnum.eLifePanType.HurtLife, 6400, false, true, -7, "BulletGround2")},
                {11014, new Bullet(11014, "九头蛇柏发出蛇头打人", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Ellipse, 2.85f, 210f, new float[] {10f,10f}, true, 0, 850, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1004}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "Spine/VFX/Monster/Prefabs/JiuTouSheBai/SnakeDown", 1f, 0, 2200, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 3f, 1009, 0, false, 1300, false, "", "", "", 0, 2.25f, false, AutoEnum.eLifePanType.Normal, 0, true, false, -7, "BulletGround2")},
                {11015, new Bullet(11015, "九头蛇柏插入地下", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Ellipse, 0f, 210f, new float[] {10f,10f}, true, 0, 350, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1001}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "", 1f, 0, 500, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 0f, 1009, 0, false, 1202, false, "", "", "", 0, 0f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11016, new Bullet(11016, "九头扫人A", AutoEnum.eBallistics.Line, 1.25f, AutoEnum.eRangeType.Ellipse, 3f, 210f, new float[] {10f,10f}, true, 0, 335, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1024}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "", 1f, 0, 1200, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1900, false, "", "", "", 0, 18f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11017, new Bullet(11017, "九头扫人C", AutoEnum.eBallistics.Line, 1.25f, AutoEnum.eRangeType.Ellipse, 3f, 210f, new float[] {10f,10f}, true, 0, 335, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1024}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 180, 0f, "", 1f, 0, 1200, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1900, false, "", "", "", 0, 13f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11018, new Bullet(11018, "尸鳖普攻", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Cube, 2f, 210f, new float[] {2.85f,2.85f}, true, 0, 20, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "", 1f, 0, 250, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1f, 0, 0, false, 700, false, "", "", "", 0, 1.65f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11019, new Bullet(11019, "血尸普攻", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Cube, 2f, 210f, new float[] {6.25f,6.25f}, true, 0, 100, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1026}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Character}, 0, 0f, "", 1f, 0, 550, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1f, 0, 0, false, 700, false, "", "", "", 0, 1.65f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11020, new Bullet(11020, "潘子普攻射箭", AutoEnum.eBallistics.Line, 23.5f, AutoEnum.eRangeType.Cube, 4f, 40f, new float[] {3.75f,2.2f}, true, 1, 30, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 1.5f, "Spine/VFX/Bullet/Jian", 1f, 0, 675, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1f, 1009, 0, false, 600, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11021, new Bullet(11021, "潘子剑雨", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Ellipse, 6f, 40f, new float[] {10f,10f}, true, 0, 200, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1021}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "Spine/VFX/Prefabs/PanZi/JianYu", 2f, 0, 1800, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2.5f, 1009, 0, false, 235, true, "Spine/VFX/Prefabs/PanZi/JianYu", "Spine/VFX/Prefabs/PanZi/JianYu", "Spine/VFX/Prefabs/PanZi/JianYu", 0, 4.05f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11022, new Bullet(11022, "表现爆裂箭", AutoEnum.eBallistics.Line, 8f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 1000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, -2f, "", 1f, 0, 700, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11023, new Bullet(11023, "潘子挂buff", AutoEnum.eBallistics.Line, 0f, AutoEnum.eRangeType.Cube, 0f, 40f, new float[] {1f,1f}, true, 1, 10, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1027,1028}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.PlayerSelf}, 0, 0f, "Spine/VFX/Prefabs/Buff", 1f, 0, 500, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 0f, 0, 0, false, 1000, false, "", "", "", 0, 0f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround2")},
                {11024, new Bullet(11024, "表现分爆裂箭", AutoEnum.eBallistics.Line, 8f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, -2f, "", 1f, 0, 700, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11025, new Bullet(11025, "表现分爆裂箭", AutoEnum.eBallistics.Line, 8f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 12, -2f, "", 1f, 0, 700, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11026, new Bullet(11026, "表现分爆裂箭", AutoEnum.eBallistics.Line, 8f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, -12, -2f, "", 1f, 0, 700, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11027, new Bullet(11027, "实际伤害多发爆裂箭", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11028, new Bullet(11028, "伤害分爆裂箭1", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11029, new Bullet(11029, "伤害分爆裂箭2", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 12, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11030, new Bullet(11030, "伤害分爆裂箭3", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, -12, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11031, new Bullet(11031, "小哥测试普攻踢腿", AutoEnum.eBallistics.Line, 17f, AutoEnum.eRangeType.Cube, 4f, 40f, new float[] {4.75f,2.7f}, true, 0, 95, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1025}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, -1f, "", 1f, 0, 770, 500, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 4f, 1009, 0, false, 750, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11032, new Bullet(11032, "假小哥测试声波攻击", AutoEnum.eBallistics.Line, 7.5f, AutoEnum.eRangeType.Cube, 6f, 40f, new float[] {2.25f,5f}, true, 0, 125, 10, 0f, AutoEnum.eDamageType.Physic, new Int64[] {1021}, new Int64[] {2}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "", 1f, 0, 750, 500, 1.5f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.None}, 2.5f, 1010, 0, false, 1000, false, "", "", "", 0, 5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11033, new Bullet(11033, "伤害多发爆裂箭2", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, -2, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11034, new Bullet(11034, "伤害多发爆裂箭3", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 2, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11035, new Bullet(11035, "伤害多发爆裂箭4", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {0f,0f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 1, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11036, new Bullet(11036, "伤害多发爆裂箭5", AutoEnum.eBallistics.Line, 23f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 2000, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, -1, 0f, "Spine/VFX/Bullet/BaoLieJian_1", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11037, new Bullet(11037, "zhen伤害多发爆裂箭1", AutoEnum.eBallistics.Line, 28f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 35, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11038, new Bullet(11038, "zhen伤害多发爆裂箭2", AutoEnum.eBallistics.Line, 28f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 35, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, -2, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11039, new Bullet(11039, "zhen伤害多发爆裂箭3", AutoEnum.eBallistics.Line, 28f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 35, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 2, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11040, new Bullet(11040, "zhen伤害多发爆裂箭4", AutoEnum.eBallistics.Line, 28f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 35, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 1, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11041, new Bullet(11041, "zhen伤害多发爆裂箭5", AutoEnum.eBallistics.Line, 28f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 35, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, -1, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 2f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11042, new Bullet(11042, "zhen伤害分爆裂箭1", AutoEnum.eBallistics.Line, 29f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 75, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 0, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11043, new Bullet(11043, "zhen伤害分爆裂箭2", AutoEnum.eBallistics.Line, 29f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 75, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, 12, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
                {11044, new Bullet(11044, "zhen伤害分爆裂箭3", AutoEnum.eBallistics.Line, 29f, AutoEnum.eRangeType.Cube, 10f, 40f, new float[] {4.5f,1.25f}, true, 0, 75, 25, 0f, AutoEnum.eDamageType.Physic, new Int64[] {-1}, new Int64[] {1}, new AutoEnum.eTargetType[] {AutoEnum.eTargetType.Monster,AutoEnum.eTargetType.Boss,AutoEnum.eTargetType.EnemyCharacter}, -12, 0f, "", 1f, 1026, 700, 350, 0f, new AutoEnum.ePhysicType[] {AutoEnum.ePhysicType.StrengthWall}, 1.5f, 1009, 0, false, 1000, false, "", "", "", 0, 2.5f, false, AutoEnum.eLifePanType.Normal, 0, true, false, 0, "BulletGround")},
            }
        );
        public static Bullet Get(Int64 id) {
            Bullet config = null; if (Datas.TryGetValue(id, out config)) return config; return null;
        }
    }
}
